### ISSUE TITLE
Setup release workflow (+ do initial release)

### ISSUE THREAD

**Issue by G-Rath** [jest-community/eslint-plugin-jest-extended#2]
While the release workflow exists, it's currently not setup to publish (iirc its not got a token?).

We should get that sorted and release v1 so people can start using this 🎉 

(I've not actually got the access writes needed to do this, so @SimenB or @mattphillips could either of you action this?)

**Comment by SimenB** [comment]
I don't have publish access unfortunately

**Comment by Arttse** [comment]
@mattphillips is there any chance to resolve this? We need to be able to install this great plugin via NPM. Thank you very much ❤️

**Comment by ge65cer** [comment]
Hey, any news on this issue? I would love to start using these ESLint rules for jest-extended. 🙂

**Comment by G-Rath** [comment]
@ge65cer no I've not seen any activity from @mattphillips (I'm hoping he's ok ❤️).

I don't really use Twitter, but someone who does could try reaching out to him there - we could also try reaching out to npm but I don't think we'll get very far due to their change in policy around transferring packages when the owner cannot be contacted (which last I checked is now "we don't").

**Comment by G-Rath** [comment]
So I've reached out to npm support, who replied saying (among other things):

> We are experiencing a massive backlog with package transfer requests. This process is currently taking about 3-4 months. We appreciate your patience as we work through each request first in first serve.

Still at least it sounds like they're not outright saying "no" so 🤞

**Comment by mattphillips** [comment]
Hey guys sorry for the silence, I’m currently away travelling and don’t have a laptop with me. 

When I’m back in a few days I’ll get the package transferred to the jest-community org on npm so more people than me have access to publish it 👍

**Comment by mattphillips** [comment]
@G-Rath I've added the package to the jest-community org on npm now so others have publishing access should I be unavailable again! In terms of the automated releases I've not set that up before and it looks like the workflow hasn't been touched in 2 years so it might be worth someone taking a look over it and see what needs doing and then we can get a token generated.

cc/ @SimenB

**Comment by G-Rath** [comment]
@mattphillips awesome thanks! The workflow for everyone hasn't changed in the last couple of years, so it should still be good to go but I will give things a general update anyway since currently we're supporting Node 8 whereas `eslint-plugin-jest` now requires Node 12 or higher.

**Comment by G-Rath** [comment]
@mattphillips also couple of things you could do that I can't as I'm not a member of the jest-community org: change the default branch to `main` and enable ["Automatically delete head branches"](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches)

**Comment by G-Rath** [comment]
@mattphillips I've opened #5 updating everything including the workflows - once that's merged we should be good to do our first release.

**Comment by ge65cer** [comment]
@G-Rath @mattphillips @SimenB That's great news! Let's get this released. 🚀

**Comment by G-Rath** [comment]
@mattphillips @SimenB have assigned #6 to you to resolve 😛

**Comment by SimenB** [comment]
I've been in talks with npm support since May about issues resetting the password of my account. They're still looking into it (whatever that means), but in the meantime I don't have access to generate new tokens. So @mattphillips needs to add it (unless npm suddenly figures out what's wrong, then I can do it).

---

Merge commits were already disallowed, fwiw.

**Comment by ge65cer** [comment]
@SimenB @G-Rath @mattphillips What's the status here, any remaining blockers? 🙂

**Comment by G-Rath** [comment]
@ge65cer nothing has changed since my comment - we're needing @mattphillips to setup the npm token for publishing.

**Comment by mattphillips** [comment]
@G-Rath I've added a token for publishing so you should be good to go now 🙏

**Comment by SimenB** [comment]
Tweaked the readme to trigger a CI run

**Comment by SimenB** [comment]
And enabled renovate

**Comment by SimenB** [comment]
https://github.com/jest-community/eslint-plugin-jest-extended/releases/tag/v1.0.0

**Comment by G-Rath** [comment]
@SimenB thanks for that!
