### ISSUE TITLE
prefer-to-be: Prefer toBeTrue, toBeFalse instead of toBe(true), toBe(false)

### ISSUE THREAD

**Issue by ilyub** [jest-community/eslint-plugin-jest-extended#3]
prefer-to-be already prefers toBeUndefined instead of toBe(undefined).

I suggest also to prefer toBeTrue, toBeFalse instead of toBe(true), toBe(false).

**Comment by G-Rath** [comment]
I've transferred this to here because those matchers are only in `jest-extended` - this is a very good idea, but unfortunately we're blocked by not being able to release: #2

cc @mattphillips

**Comment by G-Rath** [comment]
(though actually we sort of already do this as I wrote `prefer-to-be-true` and `prefer-to-be-false` 😅 - still, I'll leave this open for now, since it's not published)

**Comment by G-Rath** [comment]
Closing as we've published v1 which includes these rules.
